### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by klarkc**
Adds docker support

Usage:

```bash
docker build -t extract .
docker run -v /path/to/repo:/repo -it extract --repo_path /repo
```

### CODE REVIEW

**Comment by klarkc** [comment]
There is an issue: If compiled binary is outdated it will keep upgrading every run, because application self re-run after an upgrade (docker container storage is re-created on each run). A simple patch on [autoupdate.go](https://github.com/codersrank-org/repo_info_extractor/blob/master/autoupdater/autoupdate.go) but I am not a golang guy :(

**Comment by peti2001** [comment]
Hi @klarkc,

I am not sure I understand what problem does the Docker support solves. We switched to Go because it is possible to build a binary and use it without any dependencies. 
Docker support definitely brings some new issues we have to solve, but I am not sure it worths it. Can you explain what is the use-case you tried to solve with Docker?

**Comment by klarkc** [comment]
> I am not sure I understand what problem does the Docker support solves. We switched to Go because it is possible to build a binary and use it without any dependencies.

I don't see other use cases for docker that a bundled binary does not already solves, except that it runs in a sandbox environment, improving security a bit. So it's just one more option to distribute code.

**Comment by peti2001** [comment]
I created a feature request: https://codersrank.canny.io/feature-request/p/dockerize-the-repoinfoextractor. Let's see if there is demand for it we can implement and fix the above issues.

**Pull request closed without merging**
