### PR TITLE
fixed multifile git path in windows.

### PR DESCRIPTION
**Pull request by dvgamerr**
```
Error during getting commits. Error: exec: "C:\\Program Files\\Git\\cmd\\git.exe\r\nC:\\Program Files\\Git\\mingw64\\bin\\git.exe": file does not exist
```

fixed, please review.

### CODE REVIEW

**Comment by peti2001** [comment]
As I can see the problem is the trailing whitespace characters. Wouldn't it be easier to use `strings.TrimSpace` (https://golang.org/pkg/strings/#TrimSpace)?

**Comment by dvgamerr** [comment]
Because I don't know Why did the original code use `strings.TrimRight`, so I keep using it as before.

**Comment by peti2001** [comment]
I might found a better solution. Can you please give it a try? If it solves your problem I can merge it. Here is the branch: https://github.com/codersrank-org/repo_info_extractor/tree/improve_git_detect

**Comment by dvgamerr** [comment]
It works.

image

**Comment by peti2001** [comment]
Ohh, I accidentally merged this PR. I revert it and merge the `improve_git_detect` branch.

**Pull request merged**
