### PR TITLE
Added tests for R

### PR DESCRIPTION
**Pull request by kitswas**
Added tests as requested - https://github.com/codersrank-org/libraries/pull/129#issuecomment-1195465021

### CODE REVIEW

**Comment by krogucci** [comment]
Thanks so much @kitswas! Our team will have a look soon.

**Comment by kitswas** [comment]
@krogucci 
Do keep me updated on your team's progress. Also tell me if there is something I can do.

**Comment by peti2001** [comment]
Hi @kitswas,

I am working on this. I had some progress. It looks like you can expect it around the second part of the next week.

**Comment by peti2001** [comment]
I had a free hour so I implemented it. 

It is already deployed. Enjoy! :)

**Comment by kitswas** [comment]
Unfortunately, this does not seem to be working. No R libraries are being detected.
However, the regexes capture the library names correctly. Tested on [regex101](https://regex101.com/).

In the generated JSON file, the following part should have the `Shiny` library:

```json
,{"fileName":"d2a57dc1d883fd21fb9951699df71cc7.R","insertions":58,"deletions":0,"language":"R"}],"libraries":{}}
```

**Comment by peti2001** [comment]
Thanks for checking it. It is supposed to be working now:
```
..."insertions":31,"deletions":0,"language":"R"}],"libraries":{"R":["googlesheets","gmailr","glue","purrr"]}}
```

**Pull request merged**
