### PR TITLE
Fix permissions error for `pip install`

### LINKED ISSUE #26: Permissions error
```
> ./install.sh
...
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->GitPython==2.1.11->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/55/d2/866d45e3a121ee15a1dc013824d58072fd5c7799c9c34d01378eb262ca8f/smmap2-2.0.5-py2.py3-none-any.whl
Installing collected packages: smmap2, gitdb2, GitPython, prompt-toolkit, regex, whaaaaat, requests-toolbelt
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/lib/python3.7/site-packages/smmap2-2.0.5.dist-info'
```

Arch Linux, `pip` installed as package: https://www.archlinux.org/packages/extra/any/python-pip/

### PR DESCRIPTION
**Pull request by AlexWayfer**
Resolve #26.

### CODE REVIEW

**Comment by peti2001** [comment]
We need to test it in different environments.

**Comment by AlexWayfer** [comment]
> We need to test it in different environments.

OK. I personally suggest to test with `python2`.

**Comment by MarvinKweyu** [comment]
Don't you think it would be better to keep the testing more on python 3 given python2 has no more support soon?

**Comment by AlexWayfer** [comment]
> Don't you think it would be better to keep the testing more on python 3 given python2 has no more support soon?

Is this question for me? I think that we should not support `python2`, and I'm using `python3`, but if collaborators want to test in different environments — I just suggest to test with `python2`, because some environments can has no `python3` and I didn't test this patch with `python2`. 

If collaborators don't care about `python2` (I didn't see any info about python version in README) — it's fine for me.

**Comment by MarvinKweyu** [comment]
I think the `pip install --user -r requirements.txt ` would work perfectly for Ark based linux distributions. So that would definately work :+1:

**Pull request closed without merging**
