### PR TITLE
Extract libraries from swift

### LINKED ISSUE #48: Extract libraries from Swift
# Introduction
We started to implement the `external library recognition` feature.
It means the `repo_info_extractor` will be able to recognize the used libraries and not just the programming language.

# How does it work?
Regexes are used to recognize library imports.
This library detection must be done language by language since each language has a different syntax to import libraries. 
We created a [`JavaScript` extractor](https://github.com/codersrank-org/repo_info_extractor/blob/master/src/language/JavaScript.py) as the first working library extractor. 

# Requirements
- Create a new extractor for Swift.
- Place the new file here: https://github.com/codersrank-org/repo_info_extractor/tree/master/src/language
- Implement the `def extract_libraries(files):` function. The input this an array of paths to the files. The output is an array of the recognized libraries.
- Add UnitTest too here: https://github.com/codersrank-org/repo_info_extractor/tree/master/test

### PR DESCRIPTION
**Pull request by rabxly**
Added library extraction for Swift. Closes #48

### CODE REVIEW

**Comment by peti2001** [comment]
When I run the tests I have this error:
```
..E.../Users/pkarakas/anaconda2/envs/ra3/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.22.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/Users/pkarakas/anaconda2/envs/ra3/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 0.22.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
.......
======================================================================
ERROR: test_Swift.transplant_class.<locals>.C (test_extract_libraries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pkarakas/Work/python/repo_info_extractor/test/test_Swift.py", line 12, in test_extract_libraries
    assert libs['Swift'] == [
KeyError: 'Swift'

----------------------------------------------------------------------
Ran 13 tests in 2.430s

FAILED (errors=1)
(ra3)
```

The Docker image build fails with the same error too.

**Comment by rabxly** [comment]
I have added a fix. Now it works fine on local, but the test still seems to fail. Can you check please?

**Comment by peti2001** [comment]
Try the test like this:
```python
import os
from language.Swift import extract_libraries


def test_extract_libraries():
    dir_path = os.path.dirname(os.path.realpath(__file__))
    files = ['fixtures/Swift.swift']
    fq_files = [os.path.join(dir_path, f) for f in files]
    libs = extract_libraries(fq_files)
    assert len(libs['Swift']) == 15

    assert 'Cocoa' in libs['Swift']
    assert 'os.log' in libs['Swift']
    assert 'StatsKit' in libs['Swift']
    assert 'ModuleKit' in libs['Swift']
    assert 'CPU' in libs['Swift']
    assert 'Disk' in libs['Swift']
    assert 'Memory' in libs['Swift']
    assert 'Net' in libs['Swift']
    assert 'Battery' in libs['Swift']
    assert 'Sensors' in libs['Swift']
    assert 'GPU' in libs['Swift']
    assert 'Fans' in libs['Swift']
    assert 'CoreServices.DictionaryServices' in libs['Swift']
    assert 'Pentathlon.swim' in libs['Swift']
    assert 'test.test' in libs['Swift']
```

**Comment by rabxly** [comment]
Hi,
I have changed the test according to you suggestions. It works on local. Could you check the Docker image?

**Comment by peti2001** [comment]
yes, it works.

**Pull request merged**
