### PR TITLE
Fix No module named 'gitdb.utils.compat'

### PR DESCRIPTION
**Pull request by CoolGoose**

### CODE REVIEW

**Comment by peti2001** [comment]
Thanks for your contribution. It is not solving all the problems but helped to move toward the right solution.
I am pushing the fix soon.

**Comment by CoolGoose** [comment]
@peti2001 fyi that was enough for me to make it work and update my profile :)

**Comment by peti2001** [comment]
Yes, indeed.
`make docker` was still failing. But now it is fixed. After your PR, it was easy :).

**Comment by peti2001** [comment]
Hi @CoolGoose,

We are planning to rewrite the repo_info_extractor. I collected the plans here #160, feel free to share your thoughts.

**Pull request merged**
